[package]
name = "bin"
version = "0.1.0"
edition = "2021"

[dependencies]
mdns-sd = "0.11.5"
rairplay = { path = "../lib" }
tokio = { version = "1.41.1", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
