[package]
name = "rairplay-bin"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1.40"
tracing-subscriber = "0.3.19"
mdns-sd = "0.11.5"
rairplay = { path = "../lib" }

httparse = "1"
pin-project-lite = "0.2"
tower = "0.5"
hyper = { version = "1", features = ["server", "http1"] }
hyper-util = { version = "0.1", features = ["tokio"] }
tokio = { version = "1.41.1", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec", "io"] }
